#!/bin/python3

import math
import os
import random
import re
import sys

Num = int(input().strip())
for i in range(1, 11): 
    answer = i * Num
    print(str(Num) + " x " + str(i) + " = " + str(answer))
