#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    num = int(input())

    array = list(map(int, input().rstrip().split()))

    for i in range(num//2):
        array[i], array[-1 * (i + 1)] = array[-1 * (i + 1)], array[i]
    
    print(*array)
